version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: shrimp_farm_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - shrimp_farm_network

networks:
  shrimp_farm_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
