version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: shrimp_farm_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - shrimp_farm_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shrimp_farm_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/shrimpfarm?authSource=admin
      - PORT=5001
    depends_on:
      - mongodb
    networks:
      - shrimp_farm_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shrimp_farm_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    networks:
      - shrimp_farm_network

networks:
  shrimp_farm_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local